version: "3.8"

services:
  db:
    platform: linux/arm64
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -u root --password=mt110711@ -P 3306"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - db
    image: wod-java
    restart: on-failure
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?serverTimezone=UTC",
      "spring.datasource.username" : "$MYSQL_USER",
      "spring.datasource.password" : "$MYSQL_PASSWORD",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
      "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
      "stripe.api.publicKey" : ,
      "stripe.api.secretKey" : ,
      "spring.mail.username" : "$USER_EMAIL",
      "jwt.expiration" : "604800000",
      "jwt.secret" : "hellomatesfasdasfgmmnvbuiaspkfpojma"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
